# Generated by Django 6.0.5 on 2026-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
